logging:
  file:
    name: app.log
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
    depavlo:
      mediaprocess: DEBUG 
  pattern:
    #console: '%highlight(%-5level) %green(%C{1.}):[%L - %msg%n%throwable'
    console:
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: root
    url: jdbc:mariadb://192.168.123.6:3306/mediarepo
    #url: jdbc:mariadb://192.168.88.6:3306/mediarepo
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        ##dialect: org.hibernate.dialect.MariaDB103Dialect
        show_sql: false
        type: 'TRACE '
        use_sql_comments: true
